apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp1
  labels:
    app: dp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: co1
          image: shaikmustafa/cycle
          ports:
            - containerPort: 80
